# Generated by Django 4.2.6 on 2023-10-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='is_active',
        ),
    ]
