# Generated by Django 4.2.6 on 2023-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_otpcode_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
