# Generated by Django 4.2.6 on 2023-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otpcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
